FROM tomcat:9.0-jdk21-temurin

# Remove default Tomcat applications
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR generated by Maven
COPY onlinebookstore/target/*.war /usr/local/tomcat/webapps/ROOT.war

# Tomcat listens on 8181
EXPOSE 8181

# Start Tomcat
CMD ["catalina.sh", "run"]
