# Generated by Django 5.2.9 on 2025-12-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='audio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='answers',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
