# Generated by Django 5.2.9 on 2025-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_answers_audio_alter_answers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
