# Generated by Django 5.2.9 on 2026-01-01 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_answers_marks'),
        ('teachers', '0006_alter_questions_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.questionoption'),
        ),
    ]
