# Generated by Django 5.2.9 on 2026-01-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_answers_option'),
        ('teachers', '0006_alter_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='teachers.questionoption'),
        ),
    ]
