# Generated by Django 5.2.9 on 2026-01-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_answers_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='audio',
        ),
    ]
