# Generated by Django 5.2.9 on 2026-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_answers_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='status',
            field=models.CharField(default='unattempted', max_length=20),
        ),
    ]
