# Generated by Django 5.2.9 on 2026-01-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_answers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
