# Generated by Django 5.2.9 on 2026-01-12 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_matchedpair'),
        ('teachers', '0009_alter_questions_question_type_matchitem_matchpair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='option',
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_match_pairs', to='students.answers')),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.matchitem')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.matchitem')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='students.answers')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='teachers.questionoption')),
            ],
        ),
        migrations.DeleteModel(
            name='MatchedPair',
        ),
    ]
