# Generated by Django 5.2.9 on 2026-01-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_answers_option_matchpair_selectedoption_and_more'),
        ('teachers', '0009_alter_questions_question_type_matchitem_matchpair'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchPair',
            new_name='MatchedPair',
        ),
    ]
