# Generated by Django 5.2.9 on 2026-01-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_matchpair_matchedpair'),
        ('teachers', '0009_alter_questions_question_type_matchitem_matchpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.questionoption'),
        ),
    ]
