# Generated by Django 5.2.9 on 2026-01-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_selectedoption_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedoption',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='students.selectedoption'),
        ),
    ]
