# Generated by Django 5.2.9 on 2026-01-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_selectedoption_answer_answers_option'),
        ('teachers', '0009_alter_questions_question_type_matchitem_matchpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='teachers.questionoption'),
        ),
        migrations.DeleteModel(
            name='SelectedOption',
        ),
    ]
