# Generated by Django 5.2.9 on 2026-01-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_answers_option_delete_selectedoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='marks',
        ),
    ]
