# Generated by Django 5.2.9 on 2026-02-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_answers_marks'),
        ('teachers', '0012_alter_questions_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.answers')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.questionoption')),
            ],
        ),
    ]
