# Generated by Django 5.2.9 on 2026-02-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_selectedoption'),
        ('teachers', '0012_alter_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedoption',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='students.answers'),
        ),
        migrations.AlterField(
            model_name='selectedoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.questionoption'),
        ),
    ]
