# Generated by Django 5.2.9 on 2026-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
