# Generated by Django 5.2.9 on 2026-04-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_attempts_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='retake',
            field=models.BooleanField(default=False),
        ),
    ]
