# Generated by Django 5.2.9 on 2026-04-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_attempts_retake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempts',
            options={'ordering': ['-start_time']},
        ),
    ]
