# Generated by Django 5.2.9 on 2026-04-15 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_attempts_options'),
        ('teachers', '0023_tests_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('speech', 'Speech'), ('keyboard', 'Keyboard')], default='speech')),
                ('type', models.CharField(choices=[('info', 'Info'), ('command', 'Command'), ('answer', 'Answer'), ('violation', 'Violation'), ('other', 'Other')], default='command')),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('audio_filename', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'test', '-version'], name='testlog_version_idx'), models.Index(fields=['test', '-timestamp'], name='testlog_test_time_idx')],
            },
        ),
    ]
