# Generated by Django 5.2.9 on 2026-04-15 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_testlog'),
        ('teachers', '0023_tests_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestLog',
            new_name='TestLogs',
        ),
    ]
