# Generated by Django 5.2.9 on 2026-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_rename_testlog_testlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlogs',
            name='mode',
            field=models.CharField(choices=[('speech', 'Speech'), ('system', 'System'), ('keyboard', 'Keyboard')], default='speech'),
        ),
    ]
