# Generated by Django 5.2.9 on 2026-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_testlogs_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlogs',
            name='function',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
