# Generated by Django 5.2.9 on 2026-04-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_testlogs_function'),
        ('teachers', '0023_tests_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlogs',
            name='mode',
            field=models.CharField(choices=[('speech', 'Speech'), ('system', 'System'), ('keyboard', 'Keyboard')], default='system'),
        ),
        migrations.AlterField(
            model_name='testlogs',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.tests'),
        ),
        migrations.AlterField(
            model_name='testlogs',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('command', 'Command'), ('answer', 'Answer'), ('violation', 'Violation'), ('other', 'Other')], default='info'),
        ),
    ]
