# Generated by Django 5.2.9 on 2026-04-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_alter_testlogs_mode_alter_testlogs_test_and_more'),
        ('teachers', '0023_tests_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlogs',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.tests'),
        ),
    ]
