# Generated by Django 5.2.9 on 2026-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_alter_testlogs_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlogs',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
