# Generated by Django 5.2.9 on 2026-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_alter_testlogs_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlogs',
            name='page',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
