# Generated by Django 5.2.9 on 2026-04-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_testlogs_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlogs',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testlogs',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('error', 'Error'), ('command', 'Command'), ('answer', 'Answer'), ('violation', 'Violation'), ('other', 'Other')], default='info'),
        ),
    ]
