# Generated by Django 5.2.9 on 2026-04-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_testlogs_ip_address_alter_testlogs_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='attempts',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'Attempts'},
        ),
        migrations.AlterModelOptions(
            name='testlogs',
            options={'verbose_name_plural': 'TestLogs'},
        ),
    ]
