# Generated by Django 5.2.9 on 2026-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_alter_answers_options_alter_attempts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
