# Generated by Django 5.2.9 on 2026-05-27 14:06

import evaluate.utils.encrypt
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_attempts_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=evaluate.utils.encrypt.EncryptedTextField(),
        ),
    ]
