# Generated by Django 5.2.9 on 2026-05-27 14:06

from django.db import migrations


from django.db import migrations
import os
from cryptography.fernet import Fernet

def get_fernet():
    return Fernet(os.environ['ENCRYPTION_KEY'].encode())

def encrypt_existing(apps, schema_editor):
    fernet = get_fernet()  # initialize here, not at module level
    Answers = apps.get_model('students', 'Answers')

    for q in Answers.objects.using(schema_editor.connection.alias).iterator(chunk_size=500):
        if not q.answer:
            continue
        try:
            fernet.decrypt(q.answer.encode())  # already encrypted, skip
        except Exception:
            q.answer = fernet.encrypt(q.answer.encode()).decode()
            q.save(update_fields=['answer'])

def decrypt_all(apps, schema_editor):
    fernet = get_fernet()
    Answers = apps.get_model('students', 'Answers')

    for q in Answers.objects.using(schema_editor.connection.alias).iterator(chunk_size=500):
        if not q.answer:
            continue
        try:
            decrypted = fernet.decrypt(q.answer.encode()).decode()
            q.answer = decrypted
            q.save(update_fields=['answer'])
        except Exception:
            pass  # already plain text, skip

class Migration(migrations.Migration):
    dependencies = [
       ('students', '0033_alter_answers_answer'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing, reverse_code=decrypt_all),
    ]



