# Generated by Django 5.2.9 on 2025-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=3)),
                ('language', models.CharField(max_length=2)),
                ('service_id', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
