# Generated by Django 5.2.9 on 2026-01-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
        ('students', '0004_answers_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='students.answers')),
            ],
        ),
    ]
