# Generated by Django 5.2.9 on 2026-02-06 09:37

import speech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_answeraudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSCached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=speech.models.tts_audio_path)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
