# Generated by Django 5.2.9 on 2026-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_ttscached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechmodels',
            name='task',
            field=models.CharField(choices=[('asr', 'ASR'), ('tts', 'TTS')], max_length=3),
        ),
    ]
