# Generated by Django 5.2.9 on 2026-02-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_alter_speechmodels_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechmodels',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], max_length=2),
        ),
    ]
