# Generated by Django 5.2.9 on 2026-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_alter_speechmodels_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechmodels',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
