# Generated by Django 5.2.9 on 2025-12-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='standard',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
