# Generated by Django 5.2.9 on 2026-01-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='addresss',
            new_name='address',
        ),
    ]
