# Generated by Django 5.2.9 on 2026-02-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_addresss_institute_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institute',
            field=models.ForeignKey(default='CDAC', on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='accounts.institute'),
        ),
    ]
