# Generated by Django 5.2.9 on 2026-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exam_mode',
            field=models.CharField(choices=[('speech', 'Speech'), ('keyboard', 'Keyboard')], default='speech', max_length=8),
        ),
    ]
