# Generated by Django 5.2.9 on 2026-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
