# Generated by Django 5.2.9 on 2025-12-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_createtest_user_tests_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
