# Generated by Django 5.2.9 on 2025-12-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_tests_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='medium',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], max_length=10),
        ),
    ]
