# Generated by Django 5.2.9 on 2025-12-29 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_tests_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='medium',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='teachers.questions')),
            ],
        ),
    ]
