# Generated by Django 5.2.9 on 2025-12-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_tests_medium_questionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('TF', 'True/False')], max_length=10),
        ),
    ]
