# Generated by Django 5.2.9 on 2026-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_questions_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='unit',
        ),
        migrations.AddField(
            model_name='tests',
            name='name',
            field=models.CharField(default='test1', max_length=100),
            preserve_default=False,
        ),
    ]
