# Generated by Django 5.2.9 on 2026-01-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_remove_tests_unit_tests_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='image_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
