# Generated by Django 5.2.9 on 2026-01-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_questions_image_questions_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('TF', 'True/False'), ('FIB', 'Fill In the Blanks'), ('MTF', 'Match The Following')], max_length=10),
        ),
        migrations.CreateModel(
            name='MatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_items', to='teachers.questions')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.matchitem')),
                ('item_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.matchitem')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs', to='teachers.questions')),
            ],
        ),
    ]
