# Generated by Django 5.2.9 on 2026-02-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_questions_bank_source_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('TF', 'True or False'), ('FIB', 'Fill In the Blanks'), ('MTF', 'Match The Following')], max_length=10),
        ),
    ]
