# Generated by Django 5.2.9 on 2026-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SA', 'Short Answer'), ('LA', 'Long Answer'), ('TF', 'True or False'), ('FIB', 'Fill In the Blanks'), ('MTF', 'Match The Following'), ('MSQ', 'Multiple Selection Question')], max_length=10),
        ),
    ]
