# Generated by Django 5.2.9 on 2026-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='medium',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=10),
        ),
    ]
