# Generated by Django 5.2.9 on 2026-02-24 05:12

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_tests_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='tts_model',
            field=models.CharField(blank=True, help_text='Select TTS service id for this test', max_length=100, null=True),
        ),
    ]
