# Generated by Django 5.2.9 on 2026-02-24 05:30

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_tests_tts_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='asr_model',
            field=models.CharField(blank=True, help_text='Select ASR service id for this test', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='tts_model',
            field=models.CharField(blank=True, help_text='Select TTS service id for this test', max_length=100, null=True),
        ),
    ]
