# Generated by Django 5.2.9 on 2026-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_alter_tests_tts_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='schedule',
            field=models.DateTimeField(blank=True, help_text='Schedule test for a future time. Test will be automatically activated at the scheduled time.', null=True),
        ),
    ]
