# Generated by Django 5.2.9 on 2026-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_tests_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
