# Generated by Django 5.2.9 on 2026-03-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_institute'),
        ('teachers', '0018_tests_activated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50)),
                ('message', models.CharField(default='refresh', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institute')),
            ],
        ),
    ]
