# Generated by Django 5.2.9 on 2026-03-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_testevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testevent',
            name='message',
            field=models.CharField(default='activate', max_length=20),
        ),
    ]
