# Generated by Django 5.2.9 on 2026-03-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_alter_testevent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.tests'),
            preserve_default=False,
        ),
    ]
