# Generated by Django 5.2.9 on 2026-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_testevent_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='readOnly',
            field=models.BooleanField(default=False, help_text='If true, test cannot be edited or deleted. Useful for tests that have already been taken by students.'),
        ),
    ]
