# Generated by Django 5.2.9 on 2026-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_tests_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
