# Generated by Django 5.2.9 on 2026-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_tests_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='forPractice',
            field=models.BooleanField(default=False, help_text='If true, test will be available in practice test section for students. No student activity/answers will be logged'),
        ),
    ]
