# Generated by Django 5.2.9 on 2026-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_tests_forpractice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='forPractice',
            field=models.BooleanField(default=False, help_text='If true, test will be available in practice test section for students. No  need to activate such tests.'),
        ),
    ]
