# Generated by Django 5.2.9 on 2026-05-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_gender'),
        ('teachers', '0025_alter_tests_forpractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institute')),
                ('subjects', models.ManyToManyField(blank=True, related_name='standards', to='teachers.subject')),
            ],
        ),
        migrations.AddField(
            model_name='tests',
            name='choose_standard',
            field=models.ForeignKey(blank=True, help_text='Select standard from the standard list.', null=True, on_delete=django.db.models.deletion.PROTECT, to='teachers.standard'),
        ),
        migrations.AddField(
            model_name='tests',
            name='choose_subject',
            field=models.ForeignKey(blank=True, help_text='Select subject from the subject list.', null=True, on_delete=django.db.models.deletion.PROTECT, to='teachers.subject'),
        ),
    ]
