# Generated by Django 5.2.9 on 2026-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_subject_standard_tests_choose_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_hi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_mr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
