# Generated by Django 5.2.9 on 2026-05-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_migrate_to_foreign_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='subject',
        ),
    ]
