# Generated by Django 5.2.9 on 2026-05-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_remove_tests_standard_remove_tests_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='choose_standard',
            new_name='standard',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='choose_subject',
            new_name='subject',
        ),
    ]
