# Generated by Django 5.2.9 on 2026-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_gender'),
        ('teachers', '0031_rename_choose_standard_tests_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='standard',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='standard',
            unique_together={('institute', 'standard')},
        ),
    ]
