# Generated by Django 5.2.9 on 2026-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0032_alter_standard_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='audio_file',
            field=models.CharField(blank=True, help_text='Path to the audio file for this question, if any.', max_length=80, null=True),
        ),
    ]
