# Generated by Django 5.2.9 on 2026-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_questions_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_shuffled',
            field=models.BooleanField(default=False, help_text='If true, options for this question will be shuffled for each student.'),
        ),
    ]
