# Generated by Django 5.2.9 on 2026-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_questions_is_shuffled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='signature',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
