# Generated by Django 5.2.9 on 2026-05-27 12:08

import evaluate.utils.encrypt
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_tests_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=evaluate.utils.encrypt.EncryptedTextField(),
        ),
    ]
