# Generated by Django 5.2.10 on 2026-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0038_questionpaperupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='max_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='min_words',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='is_shuffled',
            field=models.BooleanField(default=False, help_text='if checked then question order will be different for each candidate'),
        ),
    ]
